"""Add missing indices to season_entrant_engine

Revision ID: fc5998aaad10
Revises: 
Create Date: 2026-01-25 17:41:45.755667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5998aaad10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('demonym', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='continent_pkey'),
    sa.UniqueConstraint('code', name='continent_code_key'),
    sa.UniqueConstraint('name', name='continent_name_key')
    )
    op.create_table('driver_of_the_day_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=4, scale=1), nullable=True)
    )
    op.create_table('entrant',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='entrant_pkey')
    )
    op.create_index('entr_name_idx', 'entrant', ['name'], unique=False)
    op.create_table('fastest_lap',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True)
    )
    op.create_table('free_practice_1_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('free_practice_2_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('free_practice_3_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('free_practice_4_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('pit_stop',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('stop', sa.Integer(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True)
    )
    op.create_table('pre_qualifying_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('qualifying_1_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('qualifying_2_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('qualifying_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('q1', sa.String(length=20), nullable=True),
    sa.Column('q1_millis', sa.Integer(), nullable=True),
    sa.Column('q2', sa.String(length=20), nullable=True),
    sa.Column('q2_millis', sa.Integer(), nullable=True),
    sa.Column('q3', sa.String(length=20), nullable=True),
    sa.Column('q3_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('race_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('shared_car', sa.Boolean(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('time_penalty', sa.String(length=20), nullable=True),
    sa.Column('time_penalty_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('gap_laps', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('reason_retired', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pole_position', sa.Boolean(), nullable=True),
    sa.Column('qualification_position_number', sa.Integer(), nullable=True),
    sa.Column('qualification_position_text', sa.String(length=4), nullable=True),
    sa.Column('grid_position_number', sa.Integer(), nullable=True),
    sa.Column('grid_position_text', sa.String(length=2), nullable=True),
    sa.Column('positions_gained', sa.Integer(), nullable=True),
    sa.Column('pit_stops', sa.Integer(), nullable=True),
    sa.Column('fastest_lap', sa.Boolean(), nullable=True),
    sa.Column('driver_of_the_day', sa.Boolean(), nullable=True),
    sa.Column('grand_slam', sa.Boolean(), nullable=True)
    )
    op.create_table('season',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year', name='season_pkey')
    )
    op.create_table('sprint_qualifying_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('q1', sa.String(length=20), nullable=True),
    sa.Column('q1_millis', sa.Integer(), nullable=True),
    sa.Column('q2', sa.String(length=20), nullable=True),
    sa.Column('q2_millis', sa.Integer(), nullable=True),
    sa.Column('q3', sa.String(length=20), nullable=True),
    sa.Column('q3_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('sprint_race_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('time_penalty', sa.String(length=20), nullable=True),
    sa.Column('time_penalty_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('gap_laps', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('reason_retired', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('qualification_position_number', sa.Integer(), nullable=True),
    sa.Column('qualification_position_text', sa.String(length=4), nullable=True),
    sa.Column('grid_position_number', sa.Integer(), nullable=True),
    sa.Column('grid_position_text', sa.String(length=2), nullable=True),
    sa.Column('positions_gained', sa.Integer(), nullable=True)
    )
    op.create_table('sprint_starting_grid_position',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('qualification_position_number', sa.Integer(), nullable=True),
    sa.Column('qualification_position_text', sa.String(length=4), nullable=True),
    sa.Column('grid_penalty', sa.String(length=20), nullable=True),
    sa.Column('grid_penalty_positions', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True)
    )
    op.create_table('starting_grid_position',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('qualification_position_number', sa.Integer(), nullable=True),
    sa.Column('qualification_position_text', sa.String(length=4), nullable=True),
    sa.Column('grid_penalty', sa.String(length=20), nullable=True),
    sa.Column('grid_penalty_positions', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True)
    )
    op.create_table('warming_up_result',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('position_display_order', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('constructor_id', sa.String(length=100), nullable=True),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('time_millis', sa.Integer(), nullable=True),
    sa.Column('gap', sa.String(length=20), nullable=True),
    sa.Column('gap_millis', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('interval_millis', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True)
    )
    op.create_table('country',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('alpha2_code', sa.String(length=2), nullable=False),
    sa.Column('alpha3_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('continent_id', sa.String(length=100), nullable=False),
    sa.Column('ioc_code', sa.String(length=3), nullable=True),
    sa.Column('demonym', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], name='country_continent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='country_pkey'),
    sa.UniqueConstraint('alpha2_code', name='country_alpha2_code_key'),
    sa.UniqueConstraint('alpha3_code', name='country_alpha3_code_key'),
    sa.UniqueConstraint('name', name='country_name_key')
    )
    op.create_index('cntr_continent_id_idx', 'country', ['continent_id'], unique=False)
    op.create_table('circuit',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('direction', sa.String(length=14), nullable=False),
    sa.Column('place_name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('length', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('total_races_held', sa.Integer(), nullable=False),
    sa.Column('previous_names', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='circuit_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='circuit_pkey')
    )
    op.create_index('crct_country_id_idx', 'circuit', ['country_id'], unique=False)
    op.create_index('crct_direction_idx', 'circuit', ['direction'], unique=False)
    op.create_index('crct_full_name_idx', 'circuit', ['full_name'], unique=False)
    op.create_index('crct_name_idx', 'circuit', ['name'], unique=False)
    op.create_index('crct_place_name_idx', 'circuit', ['place_name'], unique=False)
    op.create_index('crct_type_idx', 'circuit', ['type'], unique=False)
    op.create_table('constructor',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(length=100), nullable=False),
    sa.Column('total_championship_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_1_and_2_finishes', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_podium_races', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_championship_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('best_championship_position', sa.Integer(), nullable=True),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='constructor_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='constructor_pkey')
    )
    op.create_index('cnst_country_id_idx', 'constructor', ['country_id'], unique=False)
    op.create_index('cnst_full_name_idx', 'constructor', ['full_name'], unique=False)
    op.create_index('cnst_name_idx', 'constructor', ['name'], unique=False)
    op.create_table('driver',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=100), nullable=False),
    sa.Column('country_of_birth_country_id', sa.String(length=100), nullable=False),
    sa.Column('nationality_country_id', sa.String(length=100), nullable=False),
    sa.Column('total_championship_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_championship_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('total_driver_of_the_day', sa.Integer(), nullable=False),
    sa.Column('total_grand_slams', sa.Integer(), nullable=False),
    sa.Column('permanent_number', sa.String(length=2), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('second_nationality_country_id', sa.String(length=100), nullable=True),
    sa.Column('best_championship_position', sa.Integer(), nullable=True),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_of_birth_country_id'], ['country.id'], name='driver_country_of_birth_country_id_fkey'),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['country.id'], name='driver_nationality_country_id_fkey'),
    sa.ForeignKeyConstraint(['second_nationality_country_id'], ['country.id'], name='driver_second_nationality_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_pkey')
    )
    op.create_index('drvr_abbreviation_idx', 'driver', ['abbreviation'], unique=False)
    op.create_index('drvr_country_of_birth_country_id_idx', 'driver', ['country_of_birth_country_id'], unique=False)
    op.create_index('drvr_date_of_birth_idx', 'driver', ['date_of_birth'], unique=False)
    op.create_index('drvr_date_of_death_idx', 'driver', ['date_of_death'], unique=False)
    op.create_index('drvr_first_name_idx', 'driver', ['first_name'], unique=False)
    op.create_index('drvr_full_name_idx', 'driver', ['full_name'], unique=False)
    op.create_index('drvr_gender_idx', 'driver', ['gender'], unique=False)
    op.create_index('drvr_last_name_idx', 'driver', ['last_name'], unique=False)
    op.create_index('drvr_name_idx', 'driver', ['name'], unique=False)
    op.create_index('drvr_nationality_country_id_idx', 'driver', ['nationality_country_id'], unique=False)
    op.create_index('drvr_permanent_number_idx', 'driver', ['permanent_number'], unique=False)
    op.create_index('drvr_place_of_birth_idx', 'driver', ['place_of_birth'], unique=False)
    op.create_index('drvr_second_nationality_country_id_idx', 'driver', ['second_nationality_country_id'], unique=False)
    op.create_table('engine_manufacturer',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(length=100), nullable=False),
    sa.Column('total_championship_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_podium_races', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_championship_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('best_championship_position', sa.Integer(), nullable=True),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='engine_manufacturer_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='engine_manufacturer_pkey')
    )
    op.create_index('enmf_country_id_idx', 'engine_manufacturer', ['country_id'], unique=False)
    op.create_index('enmf_name_idx', 'engine_manufacturer', ['name'], unique=False)
    op.create_table('grand_prix',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('total_races_held', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='grand_prix_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grand_prix_pkey')
    )
    op.create_index('grpx_abbreviation_idx', 'grand_prix', ['abbreviation'], unique=False)
    op.create_index('grpx_country_id_idx', 'grand_prix', ['country_id'], unique=False)
    op.create_index('grpx_full_name_idx', 'grand_prix', ['full_name'], unique=False)
    op.create_index('grpx_name_idx', 'grand_prix', ['name'], unique=False)
    op.create_index('grpx_short_name_idx', 'grand_prix', ['short_name'], unique=False)
    op.create_table('season_entrant',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entrant_id', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='season_entrant_country_id_fkey'),
    sa.ForeignKeyConstraint(['entrant_id'], ['entrant.id'], name='season_entrant_entrant_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_entrant_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'entrant_id', name='season_entrant_pkey')
    )
    op.create_index('sent_country_id_idx', 'season_entrant', ['country_id'], unique=False)
    op.create_index('sent_entrant_id_idx', 'season_entrant', ['entrant_id'], unique=False)
    op.create_index('sent_year_idx', 'season_entrant', ['year'], unique=False)
    op.create_table('tyre_manufacturer',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(length=100), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_podium_races', sa.Integer(), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='tyre_manufacturer_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tyre_manufacturer_pkey')
    )
    op.create_index('tymf_country_id_idx', 'tyre_manufacturer', ['country_id'], unique=False)
    op.create_index('tymf_name_idx', 'tyre_manufacturer', ['name'], unique=False)
    op.create_table('chassis',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='chassis_constructor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chassis_pkey')
    )
    op.create_index('chss_constructor_id_idx', 'chassis', ['constructor_id'], unique=False)
    op.create_index('chss_full_name_idx', 'chassis', ['full_name'], unique=False)
    op.create_index('chss_name_idx', 'chassis', ['name'], unique=False)
    op.create_table('constructor_chronology',
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('other_constructor_id', sa.String(length=100), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=False),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='constructor_chronology_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['other_constructor_id'], ['constructor.id'], name='constructor_chronology_other_constructor_id_fkey'),
    sa.PrimaryKeyConstraint('constructor_id', 'position_display_order', name='constructor_chronology_pkey'),
    sa.UniqueConstraint('constructor_id', 'other_constructor_id', 'year_from', 'year_to', name='constructor_chronology_constructor_id_other_constructor_id__key')
    )
    op.create_index('cnch_constructor_id_idx', 'constructor_chronology', ['constructor_id'], unique=False)
    op.create_index('cnch_other_constructor_id_idx', 'constructor_chronology', ['other_constructor_id'], unique=False)
    op.create_index('cnch_position_display_order_idx', 'constructor_chronology', ['position_display_order'], unique=False)
    op.create_table('driver_family_relationship',
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('other_driver_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='driver_family_relationship_driver_id_fkey'),
    sa.ForeignKeyConstraint(['other_driver_id'], ['driver.id'], name='driver_family_relationship_other_driver_id_fkey'),
    sa.PrimaryKeyConstraint('driver_id', 'position_display_order', name='driver_family_relationship_pkey'),
    sa.UniqueConstraint('driver_id', 'other_driver_id', 'type', name='driver_family_relationship_driver_id_other_driver_id_type_key')
    )
    op.create_index('dfrl_driver_id_idx', 'driver_family_relationship', ['driver_id'], unique=False)
    op.create_index('dfrl_other_driver_id_idx', 'driver_family_relationship', ['other_driver_id'], unique=False)
    op.create_index('dfrl_position_display_order_idx', 'driver_family_relationship', ['position_display_order'], unique=False)
    op.create_table('engine',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('configuration', sa.String(length=100), nullable=True),
    sa.Column('aspiration', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='engine_engine_manufacturer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='engine_pkey')
    )
    op.create_index('engn_aspiration_idx', 'engine', ['aspiration'], unique=False)
    op.create_index('engn_capacity_idx', 'engine', ['capacity'], unique=False)
    op.create_index('engn_configuration_idx', 'engine', ['configuration'], unique=False)
    op.create_index('engn_engine_manufacturer_id_idx', 'engine', ['engine_manufacturer_id'], unique=False)
    op.create_index('engn_full_name_idx', 'engine', ['full_name'], unique=False)
    op.create_index('engn_name_idx', 'engine', ['name'], unique=False)
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grand_prix_id', sa.String(length=100), nullable=False),
    sa.Column('official_name', sa.String(length=100), nullable=False),
    sa.Column('qualifying_format', sa.String(length=20), nullable=False),
    sa.Column('circuit_id', sa.String(length=100), nullable=False),
    sa.Column('circuit_type', sa.String(length=6), nullable=False),
    sa.Column('direction', sa.String(length=14), nullable=False),
    sa.Column('course_length', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('sprint_qualifying_format', sa.String(length=20), nullable=True),
    sa.Column('scheduled_laps', sa.Integer(), nullable=True),
    sa.Column('scheduled_distance', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('drivers_championship_decider', sa.Boolean(), nullable=True),
    sa.Column('constructors_championship_decider', sa.Boolean(), nullable=True),
    sa.Column('pre_qualifying_date', sa.Date(), nullable=True),
    sa.Column('pre_qualifying_time', sa.String(length=5), nullable=True),
    sa.Column('free_practice_1_date', sa.Date(), nullable=True),
    sa.Column('free_practice_1_time', sa.String(length=5), nullable=True),
    sa.Column('free_practice_2_date', sa.Date(), nullable=True),
    sa.Column('free_practice_2_time', sa.String(length=5), nullable=True),
    sa.Column('free_practice_3_date', sa.Date(), nullable=True),
    sa.Column('free_practice_3_time', sa.String(length=5), nullable=True),
    sa.Column('free_practice_4_date', sa.Date(), nullable=True),
    sa.Column('free_practice_4_time', sa.String(length=5), nullable=True),
    sa.Column('qualifying_1_date', sa.Date(), nullable=True),
    sa.Column('qualifying_1_time', sa.String(length=5), nullable=True),
    sa.Column('qualifying_2_date', sa.Date(), nullable=True),
    sa.Column('qualifying_2_time', sa.String(length=5), nullable=True),
    sa.Column('qualifying_date', sa.Date(), nullable=True),
    sa.Column('qualifying_time', sa.String(length=5), nullable=True),
    sa.Column('sprint_qualifying_date', sa.Date(), nullable=True),
    sa.Column('sprint_qualifying_time', sa.String(length=5), nullable=True),
    sa.Column('sprint_race_date', sa.Date(), nullable=True),
    sa.Column('sprint_race_time', sa.String(length=5), nullable=True),
    sa.Column('warming_up_date', sa.Date(), nullable=True),
    sa.Column('warming_up_time', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit.id'], name='race_circuit_id_fkey'),
    sa.ForeignKeyConstraint(['grand_prix_id'], ['grand_prix.id'], name='race_grand_prix_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='race_year_fkey'),
    sa.PrimaryKeyConstraint('id', name='race_pkey'),
    sa.UniqueConstraint('year', 'round', name='race_year_round_key')
    )
    op.create_index('race_circuit_id_idx', 'race', ['circuit_id'], unique=False)
    op.create_index('race_circuit_type_idx', 'race', ['circuit_type'], unique=False)
    op.create_index('race_date_idx', 'race', ['date'], unique=False)
    op.create_index('race_direction_idx', 'race', ['direction'], unique=False)
    op.create_index('race_grand_prix_id_idx', 'race', ['grand_prix_id'], unique=False)
    op.create_index('race_official_name_idx', 'race', ['official_name'], unique=False)
    op.create_index('race_qualifying_format_idx', 'race', ['qualifying_format'], unique=False)
    op.create_index('race_round_idx', 'race', ['round'], unique=False)
    op.create_index('race_sprint_qualifying_format_idx', 'race', ['sprint_qualifying_format'], unique=False)
    op.create_index('race_year_idx', 'race', ['year'], unique=False)
    op.create_table('season_constructor',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_1_and_2_finishes', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_podium_races', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_constructor_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_constructor_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'constructor_id', name='season_constructor_pkey')
    )
    op.create_index('sscn_constructor_id_idx', 'season_constructor', ['constructor_id'], unique=False)
    op.create_index('sscn_year_idx', 'season_constructor', ['year'], unique=False)
    op.create_table('season_constructor_standing',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(length=4), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_constructor_standing_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_constructor_standing_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_constructor_standing_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'position_display_order', name='season_constructor_standing_pkey')
    )
    op.create_index('sscs_constructor_id_idx', 'season_constructor_standing', ['constructor_id'], unique=False)
    op.create_index('sscs_engine_manufacturer_id_idx', 'season_constructor_standing', ['engine_manufacturer_id'], unique=False)
    op.create_index('sscs_position_display_order_idx', 'season_constructor_standing', ['position_display_order'], unique=False)
    op.create_index('sscs_position_number_idx', 'season_constructor_standing', ['position_number'], unique=False)
    op.create_index('sscs_position_text_idx', 'season_constructor_standing', ['position_text'], unique=False)
    op.create_index('sscs_year_idx', 'season_constructor_standing', ['year'], unique=False)
    op.create_table('season_driver',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('total_driver_of_the_day', sa.Integer(), nullable=False),
    sa.Column('total_grand_slams', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='season_driver_driver_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_driver_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'driver_id', name='season_driver_pkey')
    )
    op.create_index('ssdr_driver_id_idx', 'season_driver', ['driver_id'], unique=False)
    op.create_index('ssdr_year_idx', 'season_driver', ['year'], unique=False)
    op.create_table('season_driver_standing',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(length=4), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='season_driver_standing_driver_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_driver_standing_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'position_display_order', name='season_driver_standing_pkey')
    )
    op.create_index('ssds_driver_id_idx', 'season_driver_standing', ['driver_id'], unique=False)
    op.create_index('ssds_position_display_order_idx', 'season_driver_standing', ['position_display_order'], unique=False)
    op.create_index('ssds_position_number_idx', 'season_driver_standing', ['position_number'], unique=False)
    op.create_index('ssds_position_text_idx', 'season_driver_standing', ['position_text'], unique=False)
    op.create_index('ssds_year_idx', 'season_driver_standing', ['year'], unique=False)
    op.create_table('season_engine_manufacturer',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_podium_races', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=4), nullable=True),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_engine_manufacturer_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_engine_manufacturer_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'engine_manufacturer_id', name='season_engine_manufacturer_pkey')
    )
    op.create_index('ssem_engine_manufacturer_id_idx', 'season_engine_manufacturer', ['engine_manufacturer_id'], unique=False)
    op.create_index('ssem_year_idx', 'season_engine_manufacturer', ['year'], unique=False)
    op.create_table('season_entrant_constructor',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entrant_id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_entrant_constructor_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_entrant_constructor_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['entrant_id'], ['entrant.id'], name='season_entrant_constructor_entrant_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_entrant_constructor_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'entrant_id', 'constructor_id', 'engine_manufacturer_id', name='season_entrant_constructor_pkey')
    )
    op.create_index('secn_constructor_id_idx', 'season_entrant_constructor', ['constructor_id'], unique=False)
    op.create_index('secn_engine_manufacturer_id_idx', 'season_entrant_constructor', ['engine_manufacturer_id'], unique=False)
    op.create_index('secn_entrant_id_idx', 'season_entrant_constructor', ['entrant_id'], unique=False)
    op.create_index('secn_year_idx', 'season_entrant_constructor', ['year'], unique=False)
    op.create_table('season_entrant_driver',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entrant_id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('test_driver', sa.Boolean(), nullable=False),
    sa.Column('rounds', sa.String(length=100), nullable=True),
    sa.Column('rounds_text', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_entrant_driver_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='season_entrant_driver_driver_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_entrant_driver_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['entrant_id'], ['entrant.id'], name='season_entrant_driver_entrant_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_entrant_driver_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'entrant_id', 'constructor_id', 'engine_manufacturer_id', 'driver_id', name='season_entrant_driver_pkey')
    )
    op.create_index('sedr_constructor_id_idx', 'season_entrant_driver', ['constructor_id'], unique=False)
    op.create_index('sedr_driver_id_idx', 'season_entrant_driver', ['driver_id'], unique=False)
    op.create_index('sedr_engine_manufacturer_id_idx', 'season_entrant_driver', ['engine_manufacturer_id'], unique=False)
    op.create_index('sedr_entrant_id_idx', 'season_entrant_driver', ['entrant_id'], unique=False)
    op.create_index('sedr_year_idx', 'season_entrant_driver', ['year'], unique=False)
    op.create_table('season_entrant_tyre_manufacturer',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entrant_id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_entrant_tyre_manufacturer_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_entrant_tyre_manufacturer_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['entrant_id'], ['entrant.id'], name='season_entrant_tyre_manufacturer_entrant_id_fkey'),
    sa.ForeignKeyConstraint(['tyre_manufacturer_id'], ['tyre_manufacturer.id'], name='season_entrant_tyre_manufacturer_tyre_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_entrant_tyre_manufacturer_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'entrant_id', 'constructor_id', 'engine_manufacturer_id', 'tyre_manufacturer_id', name='season_entrant_tyre_manufacturer_pkey')
    )
    op.create_index('setm_constructor_id_idx', 'season_entrant_tyre_manufacturer', ['constructor_id'], unique=False)
    op.create_index('setm_engine_manufacturer_id_idx', 'season_entrant_tyre_manufacturer', ['engine_manufacturer_id'], unique=False)
    op.create_index('setm_entrant_id_idx', 'season_entrant_tyre_manufacturer', ['entrant_id'], unique=False)
    op.create_index('setm_tyre_manufacturer_id_idx', 'season_entrant_tyre_manufacturer', ['tyre_manufacturer_id'], unique=False)
    op.create_index('setm_year_idx', 'season_entrant_tyre_manufacturer', ['year'], unique=False)
    op.create_table('season_tyre_manufacturer',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('total_race_entries', sa.Integer(), nullable=False),
    sa.Column('total_race_starts', sa.Integer(), nullable=False),
    sa.Column('total_race_wins', sa.Integer(), nullable=False),
    sa.Column('total_race_laps', sa.Integer(), nullable=False),
    sa.Column('total_podiums', sa.Integer(), nullable=False),
    sa.Column('total_podium_races', sa.Integer(), nullable=False),
    sa.Column('total_pole_positions', sa.Integer(), nullable=False),
    sa.Column('total_fastest_laps', sa.Integer(), nullable=False),
    sa.Column('best_starting_grid_position', sa.Integer(), nullable=True),
    sa.Column('best_race_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tyre_manufacturer_id'], ['tyre_manufacturer.id'], name='season_tyre_manufacturer_tyre_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_tyre_manufacturer_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'tyre_manufacturer_id', name='season_tyre_manufacturer_pkey')
    )
    op.create_index('sstm_tyre_manufacturer_id_idx', 'season_tyre_manufacturer', ['tyre_manufacturer_id'], unique=False)
    op.create_index('sstm_year_idx', 'season_tyre_manufacturer', ['year'], unique=False)
    op.create_table('race_constructor_standing',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(length=4), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('positions_gained', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='race_constructor_standing_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='race_constructor_standing_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='race_constructor_standing_race_id_fkey'),
    sa.PrimaryKeyConstraint('race_id', 'position_display_order', name='race_constructor_standing_pkey')
    )
    op.create_index('rccs_constructor_id_idx', 'race_constructor_standing', ['constructor_id'], unique=False)
    op.create_index('rccs_engine_manufacturer_id_idx', 'race_constructor_standing', ['engine_manufacturer_id'], unique=False)
    op.create_index('rccs_position_display_order_idx', 'race_constructor_standing', ['position_display_order'], unique=False)
    op.create_index('rccs_position_number_idx', 'race_constructor_standing', ['position_number'], unique=False)
    op.create_index('rccs_position_text_idx', 'race_constructor_standing', ['position_text'], unique=False)
    op.create_index('rccs_race_id_idx', 'race_constructor_standing', ['race_id'], unique=False)
    op.create_table('race_data',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(length=4), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('tyre_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('practice_time', sa.String(length=20), nullable=True),
    sa.Column('practice_time_millis', sa.Integer(), nullable=True),
    sa.Column('practice_gap', sa.String(length=20), nullable=True),
    sa.Column('practice_gap_millis', sa.Integer(), nullable=True),
    sa.Column('practice_interval', sa.String(length=20), nullable=True),
    sa.Column('practice_interval_millis', sa.Integer(), nullable=True),
    sa.Column('practice_laps', sa.Integer(), nullable=True),
    sa.Column('qualifying_time', sa.String(length=20), nullable=True),
    sa.Column('qualifying_time_millis', sa.Integer(), nullable=True),
    sa.Column('qualifying_q1', sa.String(length=20), nullable=True),
    sa.Column('qualifying_q1_millis', sa.Integer(), nullable=True),
    sa.Column('qualifying_q2', sa.String(length=20), nullable=True),
    sa.Column('qualifying_q2_millis', sa.Integer(), nullable=True),
    sa.Column('qualifying_q3', sa.String(length=20), nullable=True),
    sa.Column('qualifying_q3_millis', sa.Integer(), nullable=True),
    sa.Column('qualifying_gap', sa.String(length=20), nullable=True),
    sa.Column('qualifying_gap_millis', sa.Integer(), nullable=True),
    sa.Column('qualifying_interval', sa.String(length=20), nullable=True),
    sa.Column('qualifying_interval_millis', sa.Integer(), nullable=True),
    sa.Column('qualifying_laps', sa.Integer(), nullable=True),
    sa.Column('starting_grid_position_qualification_position_number', sa.Integer(), nullable=True),
    sa.Column('starting_grid_position_qualification_position_text', sa.String(length=4), nullable=True),
    sa.Column('starting_grid_position_grid_penalty', sa.String(length=20), nullable=True),
    sa.Column('starting_grid_position_grid_penalty_positions', sa.Integer(), nullable=True),
    sa.Column('starting_grid_position_time', sa.String(length=20), nullable=True),
    sa.Column('starting_grid_position_time_millis', sa.Integer(), nullable=True),
    sa.Column('race_shared_car', sa.Boolean(), nullable=True),
    sa.Column('race_laps', sa.Integer(), nullable=True),
    sa.Column('race_time', sa.String(length=20), nullable=True),
    sa.Column('race_time_millis', sa.Integer(), nullable=True),
    sa.Column('race_time_penalty', sa.String(length=20), nullable=True),
    sa.Column('race_time_penalty_millis', sa.Integer(), nullable=True),
    sa.Column('race_gap', sa.String(length=20), nullable=True),
    sa.Column('race_gap_millis', sa.Integer(), nullable=True),
    sa.Column('race_gap_laps', sa.Integer(), nullable=True),
    sa.Column('race_interval', sa.String(length=20), nullable=True),
    sa.Column('race_interval_millis', sa.Integer(), nullable=True),
    sa.Column('race_reason_retired', sa.String(length=100), nullable=True),
    sa.Column('race_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('race_pole_position', sa.Boolean(), nullable=True),
    sa.Column('race_qualification_position_number', sa.Integer(), nullable=True),
    sa.Column('race_qualification_position_text', sa.String(length=4), nullable=True),
    sa.Column('race_grid_position_number', sa.Integer(), nullable=True),
    sa.Column('race_grid_position_text', sa.String(length=2), nullable=True),
    sa.Column('race_positions_gained', sa.Integer(), nullable=True),
    sa.Column('race_pit_stops', sa.Integer(), nullable=True),
    sa.Column('race_fastest_lap', sa.Boolean(), nullable=True),
    sa.Column('race_driver_of_the_day', sa.Boolean(), nullable=True),
    sa.Column('race_grand_slam', sa.Boolean(), nullable=True),
    sa.Column('fastest_lap_lap', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_time', sa.String(length=20), nullable=True),
    sa.Column('fastest_lap_time_millis', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_gap', sa.String(length=20), nullable=True),
    sa.Column('fastest_lap_gap_millis', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_interval', sa.String(length=20), nullable=True),
    sa.Column('fastest_lap_interval_millis', sa.Integer(), nullable=True),
    sa.Column('pit_stop_stop', sa.Integer(), nullable=True),
    sa.Column('pit_stop_lap', sa.Integer(), nullable=True),
    sa.Column('pit_stop_time', sa.String(length=20), nullable=True),
    sa.Column('pit_stop_time_millis', sa.Integer(), nullable=True),
    sa.Column('driver_of_the_day_percentage', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='race_data_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='race_data_driver_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='race_data_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='race_data_race_id_fkey'),
    sa.ForeignKeyConstraint(['tyre_manufacturer_id'], ['tyre_manufacturer.id'], name='race_data_tyre_manufacturer_id_fkey'),
    sa.PrimaryKeyConstraint('race_id', 'type', 'position_display_order', name='race_data_pkey')
    )
    op.create_index('rcda_constructor_id_idx', 'race_data', ['constructor_id'], unique=False)
    op.create_index('rcda_driver_id_idx', 'race_data', ['driver_id'], unique=False)
    op.create_index('rcda_driver_number_idx', 'race_data', ['driver_number'], unique=False)
    op.create_index('rcda_engine_manufacturer_id_idx', 'race_data', ['engine_manufacturer_id'], unique=False)
    op.create_index('rcda_position_display_order_idx', 'race_data', ['position_display_order'], unique=False)
    op.create_index('rcda_position_number_idx', 'race_data', ['position_number'], unique=False)
    op.create_index('rcda_position_text_idx', 'race_data', ['position_text'], unique=False)
    op.create_index('rcda_race_id_idx', 'race_data', ['race_id'], unique=False)
    op.create_index('rcda_type_idx', 'race_data', ['type'], unique=False)
    op.create_index('rcda_tyre_manufacturer_id_idx', 'race_data', ['tyre_manufacturer_id'], unique=False)
    op.create_table('race_driver_standing',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('position_display_order', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(length=4), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('positions_gained', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='race_driver_standing_driver_id_fkey'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='race_driver_standing_race_id_fkey'),
    sa.PrimaryKeyConstraint('race_id', 'position_display_order', name='race_driver_standing_pkey')
    )
    op.create_index('rcds_driver_id_idx', 'race_driver_standing', ['driver_id'], unique=False)
    op.create_index('rcds_position_display_order_idx', 'race_driver_standing', ['position_display_order'], unique=False)
    op.create_index('rcds_position_number_idx', 'race_driver_standing', ['position_number'], unique=False)
    op.create_index('rcds_position_text_idx', 'race_driver_standing', ['position_text'], unique=False)
    op.create_index('rcds_race_id_idx', 'race_driver_standing', ['race_id'], unique=False)
    op.create_table('season_entrant_chassis',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entrant_id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('chassis_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['chassis_id'], ['chassis.id'], name='season_entrant_chassis_chassis_id_fkey'),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_entrant_chassis_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_entrant_chassis_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['entrant_id'], ['entrant.id'], name='season_entrant_chassis_entrant_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_entrant_chassis_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'entrant_id', 'constructor_id', 'engine_manufacturer_id', 'chassis_id', name='season_entrant_chassis_pkey')
    )
    op.create_index('sech_chassis_id_idx', 'season_entrant_chassis', ['chassis_id'], unique=False)
    op.create_index('sech_constructor_id_idx', 'season_entrant_chassis', ['constructor_id'], unique=False)
    op.create_index('sech_engine_manufacturer_id_idx', 'season_entrant_chassis', ['engine_manufacturer_id'], unique=False)
    op.create_index('sech_entrant_id_idx', 'season_entrant_chassis', ['entrant_id'], unique=False)
    op.create_index('sech_year_idx', 'season_entrant_chassis', ['year'], unique=False)
    op.create_table('season_entrant_engine',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entrant_id', sa.String(length=100), nullable=False),
    sa.Column('constructor_id', sa.String(length=100), nullable=False),
    sa.Column('engine_manufacturer_id', sa.String(length=100), nullable=False),
    sa.Column('engine_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructor.id'], name='season_entrant_engine_constructor_id_fkey'),
    sa.ForeignKeyConstraint(['engine_id'], ['engine.id'], name='season_entrant_engine_engine_id_fkey'),
    sa.ForeignKeyConstraint(['engine_manufacturer_id'], ['engine_manufacturer.id'], name='season_entrant_engine_engine_manufacturer_id_fkey'),
    sa.ForeignKeyConstraint(['entrant_id'], ['entrant.id'], name='season_entrant_engine_entrant_id_fkey'),
    sa.ForeignKeyConstraint(['year'], ['season.year'], name='season_entrant_engine_year_fkey'),
    sa.PrimaryKeyConstraint('year', 'entrant_id', 'constructor_id', 'engine_manufacturer_id', 'engine_id', name='season_entrant_engine_pkey')
    )
    op.create_index('seen_constructor_id_idx', 'season_entrant_engine', ['constructor_id'], unique=False)
    op.create_index('seen_engine_id_idx', 'season_entrant_engine', ['engine_id'], unique=False)
    op.create_index('seen_engine_manufacturer_id_idx', 'season_entrant_engine', ['engine_manufacturer_id'], unique=False)
    op.create_index('seen_entrant_id_idx', 'season_entrant_engine', ['entrant_id'], unique=False)
    op.create_index('seen_year_idx', 'season_entrant_engine', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('seen_year_idx', table_name='season_entrant_engine')
    op.drop_index('seen_entrant_id_idx', table_name='season_entrant_engine')
    op.drop_index('seen_engine_manufacturer_id_idx', table_name='season_entrant_engine')
    op.drop_index('seen_engine_id_idx', table_name='season_entrant_engine')
    op.drop_index('seen_constructor_id_idx', table_name='season_entrant_engine')
    op.drop_table('season_entrant_engine')
    op.drop_index('sech_year_idx', table_name='season_entrant_chassis')
    op.drop_index('sech_entrant_id_idx', table_name='season_entrant_chassis')
    op.drop_index('sech_engine_manufacturer_id_idx', table_name='season_entrant_chassis')
    op.drop_index('sech_constructor_id_idx', table_name='season_entrant_chassis')
    op.drop_index('sech_chassis_id_idx', table_name='season_entrant_chassis')
    op.drop_table('season_entrant_chassis')
    op.drop_index('rcds_race_id_idx', table_name='race_driver_standing')
    op.drop_index('rcds_position_text_idx', table_name='race_driver_standing')
    op.drop_index('rcds_position_number_idx', table_name='race_driver_standing')
    op.drop_index('rcds_position_display_order_idx', table_name='race_driver_standing')
    op.drop_index('rcds_driver_id_idx', table_name='race_driver_standing')
    op.drop_table('race_driver_standing')
    op.drop_index('rcda_tyre_manufacturer_id_idx', table_name='race_data')
    op.drop_index('rcda_type_idx', table_name='race_data')
    op.drop_index('rcda_race_id_idx', table_name='race_data')
    op.drop_index('rcda_position_text_idx', table_name='race_data')
    op.drop_index('rcda_position_number_idx', table_name='race_data')
    op.drop_index('rcda_position_display_order_idx', table_name='race_data')
    op.drop_index('rcda_engine_manufacturer_id_idx', table_name='race_data')
    op.drop_index('rcda_driver_number_idx', table_name='race_data')
    op.drop_index('rcda_driver_id_idx', table_name='race_data')
    op.drop_index('rcda_constructor_id_idx', table_name='race_data')
    op.drop_table('race_data')
    op.drop_index('rccs_race_id_idx', table_name='race_constructor_standing')
    op.drop_index('rccs_position_text_idx', table_name='race_constructor_standing')
    op.drop_index('rccs_position_number_idx', table_name='race_constructor_standing')
    op.drop_index('rccs_position_display_order_idx', table_name='race_constructor_standing')
    op.drop_index('rccs_engine_manufacturer_id_idx', table_name='race_constructor_standing')
    op.drop_index('rccs_constructor_id_idx', table_name='race_constructor_standing')
    op.drop_table('race_constructor_standing')
    op.drop_index('sstm_year_idx', table_name='season_tyre_manufacturer')
    op.drop_index('sstm_tyre_manufacturer_id_idx', table_name='season_tyre_manufacturer')
    op.drop_table('season_tyre_manufacturer')
    op.drop_index('setm_year_idx', table_name='season_entrant_tyre_manufacturer')
    op.drop_index('setm_tyre_manufacturer_id_idx', table_name='season_entrant_tyre_manufacturer')
    op.drop_index('setm_entrant_id_idx', table_name='season_entrant_tyre_manufacturer')
    op.drop_index('setm_engine_manufacturer_id_idx', table_name='season_entrant_tyre_manufacturer')
    op.drop_index('setm_constructor_id_idx', table_name='season_entrant_tyre_manufacturer')
    op.drop_table('season_entrant_tyre_manufacturer')
    op.drop_index('sedr_year_idx', table_name='season_entrant_driver')
    op.drop_index('sedr_entrant_id_idx', table_name='season_entrant_driver')
    op.drop_index('sedr_engine_manufacturer_id_idx', table_name='season_entrant_driver')
    op.drop_index('sedr_driver_id_idx', table_name='season_entrant_driver')
    op.drop_index('sedr_constructor_id_idx', table_name='season_entrant_driver')
    op.drop_table('season_entrant_driver')
    op.drop_index('secn_year_idx', table_name='season_entrant_constructor')
    op.drop_index('secn_entrant_id_idx', table_name='season_entrant_constructor')
    op.drop_index('secn_engine_manufacturer_id_idx', table_name='season_entrant_constructor')
    op.drop_index('secn_constructor_id_idx', table_name='season_entrant_constructor')
    op.drop_table('season_entrant_constructor')
    op.drop_index('ssem_year_idx', table_name='season_engine_manufacturer')
    op.drop_index('ssem_engine_manufacturer_id_idx', table_name='season_engine_manufacturer')
    op.drop_table('season_engine_manufacturer')
    op.drop_index('ssds_year_idx', table_name='season_driver_standing')
    op.drop_index('ssds_position_text_idx', table_name='season_driver_standing')
    op.drop_index('ssds_position_number_idx', table_name='season_driver_standing')
    op.drop_index('ssds_position_display_order_idx', table_name='season_driver_standing')
    op.drop_index('ssds_driver_id_idx', table_name='season_driver_standing')
    op.drop_table('season_driver_standing')
    op.drop_index('ssdr_year_idx', table_name='season_driver')
    op.drop_index('ssdr_driver_id_idx', table_name='season_driver')
    op.drop_table('season_driver')
    op.drop_index('sscs_year_idx', table_name='season_constructor_standing')
    op.drop_index('sscs_position_text_idx', table_name='season_constructor_standing')
    op.drop_index('sscs_position_number_idx', table_name='season_constructor_standing')
    op.drop_index('sscs_position_display_order_idx', table_name='season_constructor_standing')
    op.drop_index('sscs_engine_manufacturer_id_idx', table_name='season_constructor_standing')
    op.drop_index('sscs_constructor_id_idx', table_name='season_constructor_standing')
    op.drop_table('season_constructor_standing')
    op.drop_index('sscn_year_idx', table_name='season_constructor')
    op.drop_index('sscn_constructor_id_idx', table_name='season_constructor')
    op.drop_table('season_constructor')
    op.drop_index('race_year_idx', table_name='race')
    op.drop_index('race_sprint_qualifying_format_idx', table_name='race')
    op.drop_index('race_round_idx', table_name='race')
    op.drop_index('race_qualifying_format_idx', table_name='race')
    op.drop_index('race_official_name_idx', table_name='race')
    op.drop_index('race_grand_prix_id_idx', table_name='race')
    op.drop_index('race_direction_idx', table_name='race')
    op.drop_index('race_date_idx', table_name='race')
    op.drop_index('race_circuit_type_idx', table_name='race')
    op.drop_index('race_circuit_id_idx', table_name='race')
    op.drop_table('race')
    op.drop_index('engn_name_idx', table_name='engine')
    op.drop_index('engn_full_name_idx', table_name='engine')
    op.drop_index('engn_engine_manufacturer_id_idx', table_name='engine')
    op.drop_index('engn_configuration_idx', table_name='engine')
    op.drop_index('engn_capacity_idx', table_name='engine')
    op.drop_index('engn_aspiration_idx', table_name='engine')
    op.drop_table('engine')
    op.drop_index('dfrl_position_display_order_idx', table_name='driver_family_relationship')
    op.drop_index('dfrl_other_driver_id_idx', table_name='driver_family_relationship')
    op.drop_index('dfrl_driver_id_idx', table_name='driver_family_relationship')
    op.drop_table('driver_family_relationship')
    op.drop_index('cnch_position_display_order_idx', table_name='constructor_chronology')
    op.drop_index('cnch_other_constructor_id_idx', table_name='constructor_chronology')
    op.drop_index('cnch_constructor_id_idx', table_name='constructor_chronology')
    op.drop_table('constructor_chronology')
    op.drop_index('chss_name_idx', table_name='chassis')
    op.drop_index('chss_full_name_idx', table_name='chassis')
    op.drop_index('chss_constructor_id_idx', table_name='chassis')
    op.drop_table('chassis')
    op.drop_index('tymf_name_idx', table_name='tyre_manufacturer')
    op.drop_index('tymf_country_id_idx', table_name='tyre_manufacturer')
    op.drop_table('tyre_manufacturer')
    op.drop_index('sent_year_idx', table_name='season_entrant')
    op.drop_index('sent_entrant_id_idx', table_name='season_entrant')
    op.drop_index('sent_country_id_idx', table_name='season_entrant')
    op.drop_table('season_entrant')
    op.drop_index('grpx_short_name_idx', table_name='grand_prix')
    op.drop_index('grpx_name_idx', table_name='grand_prix')
    op.drop_index('grpx_full_name_idx', table_name='grand_prix')
    op.drop_index('grpx_country_id_idx', table_name='grand_prix')
    op.drop_index('grpx_abbreviation_idx', table_name='grand_prix')
    op.drop_table('grand_prix')
    op.drop_index('enmf_name_idx', table_name='engine_manufacturer')
    op.drop_index('enmf_country_id_idx', table_name='engine_manufacturer')
    op.drop_table('engine_manufacturer')
    op.drop_index('drvr_second_nationality_country_id_idx', table_name='driver')
    op.drop_index('drvr_place_of_birth_idx', table_name='driver')
    op.drop_index('drvr_permanent_number_idx', table_name='driver')
    op.drop_index('drvr_nationality_country_id_idx', table_name='driver')
    op.drop_index('drvr_name_idx', table_name='driver')
    op.drop_index('drvr_last_name_idx', table_name='driver')
    op.drop_index('drvr_gender_idx', table_name='driver')
    op.drop_index('drvr_full_name_idx', table_name='driver')
    op.drop_index('drvr_first_name_idx', table_name='driver')
    op.drop_index('drvr_date_of_death_idx', table_name='driver')
    op.drop_index('drvr_date_of_birth_idx', table_name='driver')
    op.drop_index('drvr_country_of_birth_country_id_idx', table_name='driver')
    op.drop_index('drvr_abbreviation_idx', table_name='driver')
    op.drop_table('driver')
    op.drop_index('cnst_name_idx', table_name='constructor')
    op.drop_index('cnst_full_name_idx', table_name='constructor')
    op.drop_index('cnst_country_id_idx', table_name='constructor')
    op.drop_table('constructor')
    op.drop_index('crct_type_idx', table_name='circuit')
    op.drop_index('crct_place_name_idx', table_name='circuit')
    op.drop_index('crct_name_idx', table_name='circuit')
    op.drop_index('crct_full_name_idx', table_name='circuit')
    op.drop_index('crct_direction_idx', table_name='circuit')
    op.drop_index('crct_country_id_idx', table_name='circuit')
    op.drop_table('circuit')
    op.drop_index('cntr_continent_id_idx', table_name='country')
    op.drop_table('country')
    op.drop_table('warming_up_result')
    op.drop_table('starting_grid_position')
    op.drop_table('sprint_starting_grid_position')
    op.drop_table('sprint_race_result')
    op.drop_table('sprint_qualifying_result')
    op.drop_table('season')
    op.drop_table('race_result')
    op.drop_table('qualifying_result')
    op.drop_table('qualifying_2_result')
    op.drop_table('qualifying_1_result')
    op.drop_table('pre_qualifying_result')
    op.drop_table('pit_stop')
    op.drop_table('free_practice_4_result')
    op.drop_table('free_practice_3_result')
    op.drop_table('free_practice_2_result')
    op.drop_table('free_practice_1_result')
    op.drop_table('fastest_lap')
    op.drop_index('entr_name_idx', table_name='entrant')
    op.drop_table('entrant')
    op.drop_table('driver_of_the_day_result')
    op.drop_table('continent')
    # ### end Alembic commands ###
